### ISSUE TITLE
KeyError: '1\r'

### ISSUE THREAD

**Issue by 1249959224** [chentao1999/MedicalRelationExtraction#1]
do： python run_BC5CDR.py train
INFO:tensorflow:*****************Loading training data*****************
INFO:tensorflow:Writing example 0 of 2033
Traceback (most recent call last):
  File "E:/YC/medical_retraction/MedicalRelationExtraction-master/run_BC5CDR.py", line 273, in <module>
    train()
  File "E:/YC/medical_retraction/MedicalRelationExtraction-master/run_BC5CDR.py", line 140, in train
    train_examples, label_list, config.seq_length, tokenizer)
  File "E:\YC\medical_retraction\MedicalRelationExtraction-master\text_model.py", line 102, in convert_examples_to_features
    label_id = label_map[example.label]
KeyError: '1\r'
Where should I modify it?

**Comment by ZMD177** [comment]
@1249959224 I have the same problem. How did you solve it?
